# Conceptual Design is comprised of four main parts


**[User Level Design](http://http://dev.novocraft.com/trac/trac_backup/wiki/UserConcepts) == this covers the inputs and outputs of the system from the user perspective - or user requirements. In this section we cover different experiments such as Digital Gene Expression; Chip-Seq, Variations. The user requirements should cover high level work flow for producing outputs and include references to papers, tutorials, data sources and existing software that could be useful either for reuse or for review/training. For outputs it should include presentation options such as charts, tables, pdfs, excel etc.**
--

## Application Screens

##### [Application screen](http://dev.novocraft.com/trac/trac_backup/wiki/appscreen)describe the look and feel of application modules that users visualize in the online appliance.
--

**[Application Level design](http://dev.novocraft.com/trac/trac_backup/wiki/ApplicationConcepts) == This section covers design of the application, major components with drill down to subcomponents.**


**[Data Level Design?](http://dev.novocraft.com/trac/trac_backup/wiki/DataConcepts) == This section covers data structures; data storage locations; and data referencing (URLs?)**
--

**[Development Architecture](http://dev.novocraft.com/trac/trac_backup/wiki/DevelopmentConcepts)==This section covers the development architecture in terms of Libraries, Languages and other tools or standards used to develop the system **
--

**[System Architecture](http://dev.novocraft.com/trac/trac_backup/wiki/SysArchitecture)**


