# treePanel Documentation 

Items on the treePanel are generated by sending request to "framework/ui/createtree.php", and assemble the treepanel's root nodes, nodes, folders and leafs accordingly.

Related JS and PHP files functions:

1. Generating nodes and related links for tabPanels.
  +'panelgen.js' contains function createTrees(), which will make a request to "createtree.php" each time a page is refreshed, or a node is clicked.

  + The returned request will contain a list of the names, type of nodes and related properties needed to build the branches and leafs.

2. Build toolbar and loads tabPanel according to node type.
  + Function defaultView() in 'objectviews.js' is used to generate the tabPanels.

3. Apply drag/drop behaviour to trees based on what object they hold.
  + Function checkDropRelation()

4. Generate Files and folder names in Mounted Drive
  + Function getDir()

5. The following functions found in "createtree.php" are used to generate and return the treePanel's node properties.

|| **Function name**  || **Description** 								   ||
|| loadTreeRoot()     || Setup root nodes in treepanel, according to sort type. 			   ||
|| getNodes() 	      || get remainder nodes, excluding root nodes (such as experiments, readgroup, etc... ||
|| appendResults()    || Setup Category folders for related target files (sequence level) 		   ||
|| appendCategories() || Setup Category folders summary for all experiment related to a single project 	   ||
||                    || Setup Summary of all related target nodes according to Category folders. 	   ||



# Related MySQL Database Tables 

  * category
  * job
  * project
  * target



# Code Functions and Files for treePanel 

| **Type** 	     | **File Name**       | **Function** 	   |
| Javascript (*.js)  | ui/panelgen.js      | createTrees() 	   |
| 		     | 	            	   | sortNodes() 	   |
| 		     | 	       	    	   | checkDropRelation()   |
| 		     | 		    	   | getDir()              |
| 		     | view/objectviews.js | defaultView() 	   |




| **Type** 	| **File Name**      | **Function**       |
| PHP (*.php)   | ui/createtree.php  | loadTreeRoot()     |
| 		| 		     | getNodes()         |
| 		| 		     | appendResults()    |
| 		| 		     | appendCategories() |
